change how/if TaskName is extracted
bids-standard/eye2bids pull request #88
Opened 2024-07-05 12:36 UTC by julia-pfarr

so far taskname was extracted from a line in the asc file called *RECORDED_BY* but not all have this line as it is dependent on user settings prior to data collection. If line wasn't there, TaskName appeared in the json with an empty string, which is not useful. Now, if line is not present in asc, TaskName does not appear in json unless the user defined it in the metadata.yml file.

2024-07-08 07:50 UTC, julia-pfarr commented
Actually I think we should just change it to passing it in the metadata.yml file. The ones that have the "RECORDED_BY" entry in the edf usually have the name of the code file they used, like "modif_VWM_task_v2.5_LAB.py" which is probably not the name they would choose for being written in the json. What do you think?

2024-07-08 17:24 UTC, Remi-Gau requested changes

2024-07-08 17:24 UTC, Remi-Gau commented on eye2bids/_base.py
> +    TaskName: bool
Not sure we need to have this as an attirbute

2024-07-08 17:24 UTC, Remi-Gau commented on eye2bids/edf2bids.py
> +    if events_json.TaskName:
I think we can use a wallruss operator here.

Will explain when amin front of a proper computer.

2024-07-09 05:48 UTC, Remi-Gau commented on eye2bids/edf2bids.py
> +        events_json["TaskName"] = _extract_TaskName(events)
```suggestion
    if TaskName := _extract_TaskName(events)
        events_json["TaskName"] = TaskName
```

2024-07-09 05:50 UTC, Remi-Gau commented on eye2bids/edf2bids.py
> +    events_json.TaskName = _has_TaskName(events)
```suggestion
```

2024-07-09 05:50 UTC, Remi-Gau commented on eye2bids/edf2bids.py
> +    return not _extract_TaskName(events) == ""
```suggestion
```

2024-07-09 05:52 UTC, Remi-Gau commented on eye2bids/edf2bids.py
> +        events_json["TaskName"] = _extract_TaskName(events)
walrus operator `:=` in this case is equivalent to 

```python
TaskName = _extract_TaskName(events)
if TaskName:
   ...
```

and the empty string `""` will evaluate as a falsy.

```python
>>> if not  "":
...     print('foo')
... 
foo
```

2024-07-09 05:53 UTC, Remi-Gau commented on eye2bids/_base.py
> +    TaskName: bool
```suggestion
```

2024-07-09 05:55 UTC, Remi-Gau commented on eye2bids/_base.py
> +        self["TaskName"] = metadata.get("TaskName")
OK what if the data is both in the metadata and the data file we are reading from: which one takes precedence?
I think we should decide and make that a rule for all similar cases.

2024-07-09 14:35 UTC, julia-pfarr commented
@Remi-Gau as discussed earlier I included TaskName as a variable that can exclusively be given through the metadata.yml file and will not be produced by our code.

The changes only take care of the TaskName, I will deal will issue #90 in a separate PR.

2024-07-25 14:32 UTC, Remi-Gau approved these changes

2024-07-25 14:32 UTC, merged